def solution(msg):
    answer = []
    word_dict = {}
    
    for i in range(65, 65+26):
        word_dict[chr(i)] = i-64
    
    number = 27
    n = len(msg)
    max_length = 2
    i = 0

    while 0 <= i < n:
        for j in range(i+max_length, i, -1):
            if word_dict.get(msg[i:j]):
                answer.append(word_dict[msg[i:j]])
                print(f"{msg[i:j]}")
                print(f"answer출력 ###{word_dict[msg[i:j]]}###::: ", i, j)
                break
        word_dict[msg[i:j+1]] = number
        print(f"{msg[i:j+1]} 사전 추가 {number}")
        max_length = max(max_length, j - i + 1)
        print()
        number += 1
        i = j
    
    print(answer)

solution("THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS")


###

###